package degrel.visualize;

import degrel.core.Element;
import degrel.visualize.view.GraphView;
import degrel.visualize.viewmodel.SimpleGraphPresenterViewModel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class SimpleGraphPresenter extends JDialog {
    private JPanel contentPane;
    private JButton buttonCancel;
    private JPanel mainPanel;
    private JList list1;
    private SimpleGraphPresenterViewModel viewmodel;

    public SimpleGraphPresenter(SimpleGraphPresenterViewModel vm) {
        this.viewmodel = vm;
        $$$setupUI$$$();
        setContentPane(contentPane);
        setModal(false);
        getRootPane().setDefaultButton(buttonCancel);

        buttonCancel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onCancel();
            }
        });

        // call onCancel() when cross is clicked
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                onCancel();
            }
        });

        // call onCancel() on ESCAPE
        contentPane.registerKeyboardAction(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onCancel();
            }

        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
    }

    private void onCancel() {
        viewmodel.dispose();
        dispose();
    }

    public void pushElement(Element elem) {
        viewmodel.pushElement(elem);
        this.redrawViewModel();
    }

    protected void redrawViewModel() {
    }

    private void createUIComponents() {
        mainPanel = new GraphView(viewmodel.getGraphViewModel());
        mainPanel.setPreferredSize(new Dimension(300, 300));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.setBackground(new Color(-16724941));
        contentPane.add(mainPanel, BorderLayout.CENTER);
        final JScrollPane scrollPane1 = new JScrollPane();
        mainPanel.add(scrollPane1, BorderLayout.WEST);
        list1 = new JList();
        scrollPane1.setViewportView(list1);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        mainPanel.add(panel1, BorderLayout.EAST);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        contentPane.add(panel2, BorderLayout.SOUTH);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        panel2.add(panel3, BorderLayout.EAST);
        buttonCancel = new JButton();
        buttonCancel.setText("Close");
        panel3.add(buttonCancel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
